import Head from "next/head";
import Header from "@/components/Global/Header";
import Chat from "@/components/Home/Chat";
import Roulette from "@/components/Home/Roulette";
import {useSelector} from "react-redux";
import Jackpot from "@/components/Home/Jackpot";

export default function Home() {
    const game = useSelector(state => state.general.game)
    console.log(game)
    const GameComp = () => {
        switch (game) {
            case "jackpot":
                return <Jackpot/>
            default:
                return <Roulette/>
        }
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="h-screen grid grid-rows-[max-content_auto]">
                <Header/>
                <div className="flex items-stretch p-3">
                    <Chat/>
                    <GameComp/>
                </div>
            </main>
        </>
    )
}
