import Head from "next/head";
import Image from "next/image";

import roulette from "/public/roulette.png"
import {useState} from "react";

const SpinWrapper = ({spinDeg, spinDuration}) => {
    return <div className="relative mt-10">
        <div style={{transform: `rotate(${spinDeg}deg)`, transitionDuration: `${spinDuration}ms`}}
             className={`transition-transform ease-linear`}>
            <Image src={roulette} alt="Roulette"/>
        </div>
        <div
            className="absolute w-full h-full text-5xl inset-0 flex items-center justify-center">
            15
        </div>
        <div
            className="absolute top-1/2 -right-7 -translate-y-1/2 -translate-x-1/2 border-t-[25px] border-r-[25px] border-b-[25px] border-t-transparent border-b-transparent"></div>
    </div>
}

export default function Home() {
    const [spinDeg, setSpinDeg] = useState(0)
    const [spinDuration, setSpinDuration] = useState(10000)

    function spin() {
        setSpinDeg(spinDeg => spinDeg + 1000)
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="h-screen w-screen">
                <div className="container mx-auto flex justify-center">
                    <SpinWrapper spinDeg={spinDeg} spinDuration={spinDuration}/>
                </div>
                <div className="flex justify-center mt-10">
                    <button onClick={() => spin()}>
                        Click
                    </button>
                </div>
            </main>
        </>
    )
}
