import {getSession} from "next-auth/react";
import Header from "@/components/Global/Header";
import Head from "next/head";

export default function Profile() {
   return <>
      <Head>
         <title>Profile</title>
         <meta name="description" content="Generated by create next app"/>
         <meta name="viewport" content="width=device-width, initial-scale=1"/>
         <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
         <Header/>
         <div>

         </div>
      </main>
   </>
}

export async function getServerSideProps(ctx) {
   const session = await getSession(ctx)
   if (!session){
      ctx.res.writeHead(302, { Location: '/login' });
      ctx.res.end();
   }
   return {
      props: {
         session
      }
   }
}
